# Generated by Django 4.1 on 2022-08-28 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_super_delete_supers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='catch_pharse',
            new_name='catchphrase',
        ),
    ]
